// Human Evolution Fossil Database
// Parsed from research CSV data

const FOSSIL_DATA = [
    // Earliest hominins (7.0–4.2 Ma)
    {
        id: 1,
        species: "Sahelanthropus tchadensis",
        specimen: 'TM 266-01-060-1 "Toumaï"',
        age: "7.0 ± 0.2 Ma",
        ageNumeric: 7.0,
        location: "Toros-Menalla, Chad",
        discoverer: "Djimdoumalbaye, Beauvilain; Brunet team",
        yearDiscovered: 2001,
        description: "Near-complete cranium; postcranials described 2022",
        significance: "Oldest potential hominin; anteriorly positioned foramen magnum; small non-honing canines; 360–378 cc brain",
        citation: "Brunet et al. 2002, Nature 418:145–151. DOI: 10.1038/nature00879",
        era: "earliest",
        eraLabel: "Earliest Hominins",
        images: ["1.jpg"]
    },
    {
        id: 2,
        species: "Orrorin tugenensis",
        specimen: "BAR 1002'00",
        age: "5.9 ± 0.2 Ma",
        ageNumeric: 5.9,
        location: "Tugen Hills, Kenya",
        discoverer: "Senut, Pickford",
        yearDiscovered: 2000,
        description: "Proximal femur + 20 specimens from 5+ individuals",
        significance: "Femoral evidence for bipedalism by ~6 Ma; thick enamel; elongated femoral neck",
        citation: "Senut et al. 2001, C.R. Acad. Sci. 332:137–144. DOI: 10.1016/S1251-8050(01)01529-4",
        era: "earliest",
        eraLabel: "Earliest Hominins",
        images: ["2a.png", "2b.png"]
    },
    {
        id: 3,
        species: "Ardipithecus kadabba",
        specimen: "ALA-VP-2/10 (holotype)",
        age: "5.66 ± 0.12 Ma",
        ageNumeric: 5.66,
        location: "Middle Awash, Ethiopia",
        discoverer: "Haile-Selassie",
        yearDiscovered: 1997,
        description: "Mandible + teeth; 19 specimens total",
        significance: "Links Miocene hominins to Ar. ramidus; retained honing complex; incipient bipedalism",
        citation: "Haile-Selassie 2001, Nature 412:178–181. DOI: 10.1038/35084063",
        era: "earliest",
        eraLabel: "Earliest Hominins",
        images: ["3.png"]
    },
    {
        id: 4,
        species: "Ardipithecus ramidus",
        specimen: 'ARA-VP-6/500 "Ardi"',
        age: "4.4 Ma",
        ageNumeric: 4.4,
        location: "Aramis, Ethiopia",
        discoverer: "White, Haile-Selassie",
        yearDiscovered: 1994,
        description: "~45% skeleton: skull, pelvis, hands, feet",
        significance: "Most complete early hominin; opposable big toe; bipedal pelvis; ~350 cc brain; woodland habitat",
        citation: "White et al. 2009, Science 326:64, 75–86. DOI: 10.1126/science.1175802",
        era: "earliest",
        eraLabel: "Earliest Hominins",
        images: ["4.png"]
    },
    // Australopithecus species (4.2–1.98 Ma)
    {
        id: 5,
        species: "Australopithecus anamensis",
        specimen: "KNM-KP 29281 (holotype)",
        age: "4.05 ± 0.15 Ma",
        ageNumeric: 4.05,
        location: "Kanapoi, Kenya",
        discoverer: "Nzube, M. Leakey",
        yearDiscovered: 1994,
        description: "Partial mandible with dentition",
        significance: "Type specimen; U-shaped arcade; thick enamel",
        citation: "Leakey et al. 1995, Nature 376:565–571. DOI: 10.1038/376565a0",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["5.png"]
    },
    {
        id: 6,
        species: "Australopithecus anamensis",
        specimen: "MRD-VP-1/1",
        age: "3.8 Ma",
        ageNumeric: 3.8,
        location: "Woranso-Mille, Ethiopia",
        discoverer: "Bereino, Haile-Selassie",
        yearDiscovered: 2016,
        description: "Near-complete cranium",
        significance: "First complete A. anamensis face; ~370 cc; demonstrates temporal overlap with A. afarensis",
        citation: "Haile-Selassie et al. 2019, Nature 573:214–221. DOI: 10.1038/s41586-019-1513-8",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["6.jpg"]
    },
    {
        id: 7,
        species: "Australopithecus afarensis",
        specimen: "LH 4 (holotype)",
        age: "3.65 ± 0.05 Ma",
        ageNumeric: 3.65,
        location: "Laetoli, Tanzania",
        discoverer: "M. Leakey team",
        yearDiscovered: 1974,
        description: "Mandible with 9 teeth",
        significance: "Type specimen defining species",
        citation: "Johanson et al. 1978, Kirtlandia 28:1–14",
        primaryPaperUrl: "https://www.biodiversitylibrary.org/part/202160",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["7.jpg"]
    },
    {
        id: 8,
        species: "Australopithecus afarensis",
        specimen: 'AL 288-1 "Lucy"',
        age: "3.2 Ma",
        ageNumeric: 3.2,
        location: "Hadar, Ethiopia",
        discoverer: "Johanson, Gray",
        yearDiscovered: 1974,
        description: "~40% skeleton: skull, mandible, pelvis, limbs",
        significance: "Most famous hominin; 107 cm tall; angled femur/valgus knee prove bipedalism; curved phalanges show climbing",
        citation: "Johanson & Taieb 1976, Nature 260:293–297. DOI: 10.1038/260293a0",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["8.jpg"]
    },
    {
        id: 9,
        species: "Australopithecus afarensis",
        specimen: 'DIK-1-1 "Selam"',
        age: "3.3 Ma",
        ageNumeric: 3.3,
        location: "Dikika, Ethiopia",
        discoverer: "Alemseged",
        yearDiscovered: 2000,
        description: "Near-complete juvenile: skull, hyoid, scapulae, vertebrae",
        significance: "Most complete juvenile pre-Neanderthal; gorilla-like scapula; 3-year-old female",
        citation: "Alemseged et al. 2006, Nature 443:296–301. DOI: 10.1038/nature05047",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["9.jpg"]
    },
    {
        id: 10,
        species: "Australopithecus afarensis",
        specimen: "AL 444-2",
        age: "3.0 Ma",
        ageNumeric: 3.0,
        location: "Hadar, Ethiopia",
        discoverer: "Rak",
        yearDiscovered: 1992,
        description: "Complete adult skull with mandible",
        significance: "Largest A. afarensis cranium; 519–550 cc; confirms previous reconstructions",
        citation: "Kimbel et al. 1994, Nature 368:449–451. DOI: 10.1038/368449a0",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["10.webp"]
    },
    {
        id: 11,
        species: "Australopithecus afarensis",
        specimen: 'AL 333 "First Family"',
        age: "3.20 ± 0.02 Ma",
        ageNumeric: 3.2,
        location: "Hadar, Ethiopia",
        discoverer: "Johanson team",
        yearDiscovered: 1975,
        description: "216+ specimens from 13–17 individuals",
        significance: "Group death event; demonstrates sexual dimorphism; foot arches",
        citation: "Johanson et al. 1982, Am. J. Phys. Anthropol. 57:373–402. DOI: 10.1002/ajpa.1330570402",
        primaryPaperUrl: "https://doi.org/10.1002/ajpa.1330570402",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["11a.jpg", "11b.jpg"]
    },
    {
        id: 12,
        species: "Australopithecus africanus",
        specimen: "Taung Child (holotype)",
        age: "~2.8 Ma",
        ageNumeric: 2.8,
        location: "Taung, South Africa",
        discoverer: "Dart",
        yearDiscovered: 1924,
        description: "Juvenile skull with endocast",
        significance: "First australopithecine discovered; ~405 cc; validated African human origins",
        citation: "Dart 1925, Nature 115:195–199. DOI: 10.1038/115195a0",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["12.jpg"]
    },
    {
        id: 13,
        species: "Australopithecus africanus",
        specimen: 'Sts 5 "Mrs. Ples"',
        age: "~2.5 Ma",
        ageNumeric: 2.5,
        location: "Sterkfontein, South Africa",
        discoverer: "Broom, Robinson",
        yearDiscovered: 1947,
        description: "Near-complete adult cranium",
        significance: "Most complete undistorted A. africanus skull; ~485 cc",
        citation: "Broom 1947, Nature 159:672. DOI: 10.1038/159672a0",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["13.webp"]
    },
    {
        id: 14,
        species: "Australopithecus africanus",
        specimen: 'StW 573 "Little Foot"',
        age: "3.67 ± 0.16 Ma",
        ageNumeric: 3.67,
        location: "Sterkfontein, South Africa",
        discoverer: "Clarke",
        yearDiscovered: 1994,
        description: "~90% complete skeleton",
        significance: "Most complete early hominin skeleton; ~408 cc; Clarke assigns to A. prometheus",
        citation: "Clarke & Kuman 2019, J. Hum. Evol. 134:102634. DOI: 10.1016/j.jhevol.2019.06.005",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["14.png"]
    },
    // Other Australopithecus species
    {
        id: 15,
        species: "Australopithecus garhi",
        specimen: "BOU-VP-12/130 (holotype)",
        age: "2.5 Ma",
        ageNumeric: 2.5,
        location: "Bouri, Ethiopia",
        discoverer: "Haile-Selassie; Asfaw, White team",
        yearDiscovered: 1997,
        description: "Partial cranium",
        significance: "~450 cc; large teeth; possible tool user",
        citation: "Asfaw et al. 1999, Science 284:629–635. DOI: 10.1126/science.284.5414.629",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["15.jpg"]
    },
    {
        id: 16,
        species: "Australopithecus sediba",
        specimen: 'MH1 "Karabo" (holotype)',
        age: "1.98 Ma",
        ageNumeric: 1.98,
        location: "Malapa, South Africa",
        discoverer: "Matthew Berger (age 9); L. Berger team",
        yearDiscovered: 2008,
        description: "Juvenile partial skeleton: skull, mandible, clavicle, postcranials",
        significance: "~420 cc; Homo-like features; small teeth",
        citation: "Berger et al. 2010, Science 328:195–204. DOI: 10.1126/science.1184944",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["16.jpg"]
    },
    {
        id: 17,
        species: "Australopithecus sediba",
        specimen: "MH2",
        age: "1.98 Ma",
        ageNumeric: 1.98,
        location: "Malapa, South Africa",
        discoverer: "L. Berger",
        yearDiscovered: 2008,
        description: "Adult female partial skeleton: mandible, teeth, right arm, pelvis, knee, foot",
        significance: "Most complete early hominin hand; precision grip",
        citation: "Kivell et al. 2011, Science 333:1411–1417. DOI: 10.1126/science.1202625",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["17a.jpg", "17b.jpg", "17c.jpg"]
    },
    {
        id: 18,
        species: "Australopithecus deyiremeda",
        specimen: "BRT-VP-3/1 (holotype)",
        age: "3.4 ± 0.1 Ma",
        ageNumeric: 3.4,
        location: "Woranso-Mille, Ethiopia",
        discoverer: "Haile-Selassie team",
        yearDiscovered: 2011,
        description: "Maxilla with teeth",
        significance: "First evidence of hominin coexistence in Pliocene",
        citation: "Haile-Selassie et al. 2015, Nature 521:483–488. DOI: 10.1038/nature14448",
        era: "australopithecus",
        eraLabel: "Australopithecus",
        images: ["18b.png", "18a.png"]
    },
    // Paranthropus (robust australopithecines) and Kenyanthropus (3.5–1.0 Ma)
    {
        id: 19,
        species: "Kenyanthropus platyops",
        specimen: "KNM-WT 40000 (holotype)",
        age: "3.5 Ma",
        ageNumeric: 3.5,
        location: "Lomekwi, Kenya",
        discoverer: "Erus, M. Leakey",
        yearDiscovered: 1999,
        description: "Near-complete but distorted cranium",
        significance: "Earliest flat face; challenges A. afarensis as sole ancestor; possible Lomekwian tool maker",
        citation: "Leakey et al. 2001, Nature 410:433–440. DOI: 10.1038/35068500",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["19.png"]
    },
    {
        id: 20,
        species: "Paranthropus aethiopicus",
        specimen: 'KNM-WT 17000 "Black Skull"',
        age: "2.5 Ma",
        ageNumeric: 2.5,
        location: "West Turkana, Kenya",
        discoverer: "Walker",
        yearDiscovered: 1985,
        description: "Near-complete cranium",
        significance: "410 cc; mosaic primitive/derived traits; ancestral to P. boisei",
        citation: "Walker et al. 1986, Nature 322:517–522. DOI: 10.1038/322517a0",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["20.webp"]
    },
    {
        id: 21,
        species: "Paranthropus boisei",
        specimen: 'OH 5 "Zinj/Nutcracker Man" (holotype)',
        age: "1.78 ± 0.03 Ma",
        ageNumeric: 1.78,
        location: "Olduvai, Tanzania",
        discoverer: "M. Leakey",
        yearDiscovered: 1959,
        description: "Near-complete adult male cranium",
        significance: "~530 cc; massive sagittal crest; megadont molars; shifted focus to East Africa",
        citation: "Leakey 1959, Nature 184:491–494. DOI: 10.1038/184491a0",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["21.JPG"]
    },
    {
        id: 22,
        species: "Paranthropus boisei",
        specimen: "KNM-ER 406",
        age: "1.7 Ma",
        ageNumeric: 1.7,
        location: "Koobi Fora, Kenya",
        discoverer: "R. Leakey",
        yearDiscovered: 1969,
        description: "Near-complete cranium",
        significance: "510 cc; proved coexistence with H. erectus",
        citation: "Leakey 1970, Nature 226:223–224. DOI: 10.1038/226223a0",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["22.jpg"]
    },
    {
        id: 23,
        species: "Paranthropus robustus",
        specimen: "TM 1517 (holotype)",
        age: "1.83 ± 0.18 Ma",
        ageNumeric: 1.83,
        location: "Kromdraai, South Africa",
        discoverer: "Broom",
        yearDiscovered: 1938,
        description: "Partial skull + mandible + postcranials",
        significance: "Type specimen establishing genus Paranthropus",
        citation: "Broom 1938, Nature 142:377–379. DOI: 10.1038/142377a0",
        primaryPaperUrl: "https://doi.org/10.1038/142377a0",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["23a.jpg", "23b.jpg"]
    },
    {
        id: 24,
        species: "Paranthropus robustus",
        specimen: "SK 48",
        age: "1.65 ± 0.15 Ma",
        ageNumeric: 1.65,
        location: "Swartkrans, South Africa",
        discoverer: "Broom",
        yearDiscovered: 1950,
        description: "Near-complete adult cranium",
        significance: "Best-preserved P. robustus skull prior to DNH 7",
        citation: "Broom & Robinson 1952, Transvaal Mus. Mem. 6:1–123",
        primaryPaperUrl: "https://books.google.com/books/about/Swartkrans_Ape_Man.html?id=Hqps0QEACAAJ",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["24.webp"]
    },
    {
        id: 25,
        species: "Paranthropus robustus",
        specimen: "DNH 7",
        age: "~1.7 Ma",
        ageNumeric: 1.7,
        location: "Drimolen, South Africa",
        discoverer: "Keyser",
        yearDiscovered: 1994,
        description: "Complete skull + articulated mandible",
        significance: "Most complete P. robustus; first complete dentition",
        citation: "Keyser 2000, S. Afr. J. Sci. 96:189–197",
        primaryPaperUrl: "https://servicios.educarm.es/admin/portal/templates/portal/images/ficheros/etapasEducativas/secundaria/10/secciones/379/contenidos/7306/keyser1.pdf",
        era: "paranthropus",
        eraLabel: "Paranthropus & Kenyanthropus",
        images: ["25.webp"]
    },
    // Early Homo (2.5–1.0 Ma)
    {
        id: 26,
        species: "Homo habilis",
        specimen: 'OH 7 "Jonny\'s Child" (holotype)',
        age: "1.78 ± 0.03 Ma",
        ageNumeric: 1.78,
        location: "Olduvai, Tanzania",
        discoverer: "J. Leakey",
        yearDiscovered: 1960,
        description: "Mandible + parietals + hand bones",
        significance: "Type specimen; 729–824 cc; first early Homo; associated Oldowan tools",
        citation: "Leakey et al. 1964, Nature 202:7–9. DOI: 10.1038/202007a0",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["26.jpg"]
    },
    {
        id: 27,
        species: "Homo habilis",
        specimen: 'OH 24 "Twiggy"',
        age: "~1.8 Ma",
        ageNumeric: 1.8,
        location: "Olduvai, Tanzania",
        discoverer: "Nzube",
        yearDiscovered: 1968,
        description: "Near-complete cranium (crushed)",
        significance: "~590 cc; oldest Olduvai skull besides OH 5",
        citation: "Leakey et al. 1971, Nature 232:308–312. DOI: 10.1038/232308a0",
        primaryPaperUrl: "https://doi.org/10.1038/232308a0",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["27.webp"]
    },
    {
        id: 28,
        species: "Homo habilis",
        specimen: "KNM-ER 1813",
        age: "~1.9 Ma",
        ageNumeric: 1.9,
        location: "Koobi Fora, Kenya",
        discoverer: "Kimeu",
        yearDiscovered: 1973,
        description: "Near-complete cranium",
        significance: "510 cc; demonstrates early Homo diversity",
        citation: "Leakey 1974, Nature 248:653–656. DOI: 10.1038/248653a0",
        primaryPaperUrl: "https://doi.org/10.1038/248653a0",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["28.webp"]
    },
    {
        id: 29,
        species: "Homo rudolfensis",
        specimen: "KNM-ER 1470 (lectotype)",
        age: "1.95 ± 0.05 Ma",
        ageNumeric: 1.95,
        location: "Koobi Fora, Kenya",
        discoverer: "Ngeneo",
        yearDiscovered: 1972,
        description: "Large near-complete cranium",
        significance: "~752 cc; larger brain and flatter face than H. habilis",
        citation: "Leakey 1973, Nature 242:447–450. DOI: 10.1038/242447a0",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["29.webp"]
    },
    {
        id: 30,
        species: "Homo erectus/ergaster",
        specimen: 'KNM-WT 15000 "Turkana Boy"',
        age: "1.55 ± 0.05 Ma",
        ageNumeric: 1.55,
        location: "Nariokotome, Kenya",
        discoverer: "Kimeu, Walker, R. Leakey",
        yearDiscovered: 1984,
        description: "Most complete early human skeleton: 108 bones (~40%)",
        significance: "880 cc; 8–12 years old; modern body proportions; 1.6 m tall (adult ~1.85 m)",
        citation: "Brown et al. 1985, Nature 316:788–792. DOI: 10.1038/316788a0",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["30.png"]
    },
    {
        id: 31,
        species: "Homo erectus",
        specimen: "Trinil 2 (holotype)",
        age: "~0.9 Ma",
        ageNumeric: 0.9,
        location: "Trinil, Java, Indonesia",
        discoverer: "Dubois",
        yearDiscovered: 1891,
        description: "Calvaria",
        significance: "First recognized human ancestor outside Europe; ~900 cc; named Pithecanthropus erectus",
        citation: "Dubois 1894, Pithecanthropus erectus. Batavia: Landsdrukkerij. DOI: 10.5962/bhl.title.65514",
        primaryPaperUrl: "https://doi.org/10.5962/bhl.title.65514",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["31.webp"]
    },
    {
        id: 32,
        species: "Homo erectus",
        specimen: "Sangiran 17",
        age: "1.0 ± 0.2 Ma",
        ageNumeric: 1.0,
        location: "Sangiran, Java, Indonesia",
        discoverer: "Sartono",
        yearDiscovered: 1969,
        description: "Most complete Asian H. erectus cranium",
        significance: "~1004 cc; sagittal keel; thick vault; key Asian specimen",
        citation: "Sartono 1971, Proc. Kon. Ned. Akad. Wet. B 74:209–217",
        primaryPaperUrl: "https://books.google.com/books/about/Observations_on_a_New_Skull_of_Pithecant.html?id=-C52rgEACAAJ",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["32.webp"]
    },
    {
        id: 33,
        species: "Homo erectus",
        specimen: "Zhoukoudian (Peking Man)",
        age: "770 ± 80 ka",
        ageNumeric: 0.77,
        location: "Zhoukoudian, China",
        discoverer: "Andersson, Zdansky, Bohlin, Black",
        yearDiscovered: 1921,
        description: "6+ partial crania (lost 1941); casts preserved",
        significance: "850–1225 cc range; evidence of fire use; originals lost in WWII",
        citation: "Weidenreich 1943, Palaeontologia Sinica. New Series D 10",
        primaryPaperUrl: "https://archive.org/details/TheSkullOfSinanthropusPekinensisAComparativeStudyOnAPrimitive",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["33.webp"]
    },
    {
        id: 34,
        species: "Homo erectus",
        specimen: "Dmanisi Skull 5 (D4500/D2600)",
        age: "1.77 Ma",
        ageNumeric: 1.77,
        location: "Dmanisi, Georgia",
        discoverer: "Nioradze",
        yearDiscovered: 2000,
        description: "Complete adult skull + mandible",
        significance: "~546 cc; most complete early Homo skull; suggests single Homo species with high variation",
        citation: "Lordkipanidze et al. 2013, Science 342:326–331. DOI: 10.1126/science.1238484",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["34.jpg"]
    },
    {
        id: 35,
        species: "Homo erectus",
        specimen: "Dmanisi Skull 4 (D3444/D3900)",
        age: "1.77 Ma",
        ageNumeric: 1.77,
        location: "Dmanisi, Georgia",
        discoverer: "Lordkipanidze team",
        yearDiscovered: 2005,
        description: "Toothless elderly skull",
        significance: "Earliest evidence of care for disabled individuals",
        citation: "Lordkipanidze et al. 2006, Nature 449:305–310. DOI: 10.1038/nature06134",
        primaryPaperUrl: "https://doi.org/10.1038/nature06134",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["35.jpg"]
    },
    {
        id: 36,
        species: "Homo heidelbergensis",
        specimen: "Bodo",
        age: "600 ka",
        ageNumeric: 0.6,
        location: "Bodo d'Ar, Ethiopia",
        discoverer: "Conroy, Alemseged",
        yearDiscovered: 1976,
        description: "Large near-complete cranium",
        significance: "~1250 cc; cut marks suggest defleshing; earliest evidence of this practice",
        citation: "Rightmire 1996, Am. J. Phys. Anthropol. 100:135–153. DOI: 10.1006/jhev.1996.0046",
        primaryPaperUrl: "https://doi.org/10.1006/jhev.1996.0046",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["36.webp"]
    },
    {
        id: 37,
        species: "Homo heidelbergensis",
        specimen: "Mauer 1 (holotype)",
        age: "609 ± 40 ka",
        ageNumeric: 0.609,
        location: "Mauer, Germany",
        discoverer: "Schoetensack",
        yearDiscovered: 1907,
        description: "Complete mandible with teeth",
        significance: "Type specimen; robust mandible; no chin",
        citation: "Schoetensack 1908, Der Unterkiefer des Homo heidelbergensis. DOI: 10.1007/bf01990624",
        primaryPaperUrl: "https://www.gutenberg.org/ebooks/36382",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["37.jpg"]
    },
    {
        id: 38,
        species: "Homo heidelbergensis",
        specimen: 'Kabwe 1 "Broken Hill"',
        age: "299 ± 25 ka",
        ageNumeric: 0.299,
        location: "Kabwe, Zambia",
        discoverer: "Zwigelaar",
        yearDiscovered: 1921,
        description: "Complete cranium",
        significance: "~1280 cc; previously dated ~500–300 ka; first early human fossil from Africa",
        citation: "Grün et al. 2020, Nature 580:511–515. DOI: 10.1038/s41586-020-2165-4",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["38a.jpg", "38b.jpg"]
    },
    {
        id: 39,
        species: "Homo heidelbergensis",
        specimen: "Petralona",
        age: "~250 ± 100 ka",
        ageNumeric: 0.25,
        location: "Petralona, Greece",
        discoverer: "Poulianos",
        yearDiscovered: 1960,
        description: "Complete cranium",
        significance: "~1220 cc; mix of erectus and Neanderthal features",
        citation: "Stringer et al. 1979, J. Archaeol. Sci. 6:235–253. DOI: 10.1016/0305-4403(79)90002-5",
        primaryPaperUrl: "https://doi.org/10.1016/0305-4403(79)90002-5",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["39.webp"]
    },
    {
        id: 40,
        species: "Homo heidelbergensis",
        specimen: "Sima de los Huesos (SH)",
        age: "430 ka",
        ageNumeric: 0.43,
        location: "Atapuerca, Spain",
        discoverer: "Arsuaga team–present",
        yearDiscovered: 1984,
        description: "28+ individuals; 7000+ fossils",
        significance: "Proto-Neanderthal; largest Middle Pleistocene hominin sample; DNA extracted",
        citation: "Arsuaga et al. 2014, Science 344:1358–1363. DOI: 10.1126/science.1253958",
        era: "early-homo",
        eraLabel: "Early Homo",
        images: ["40.jpg"]
    },
    // H. naledi and island species
    {
        id: 41,
        species: "Homo naledi",
        specimen: "DH1 (holotype)",
        age: "286 ± 50 ka",
        ageNumeric: 0.286,
        location: "Rising Star Cave, South Africa",
        discoverer: "Hunter, Tucker (cavers); Berger team",
        yearDiscovered: 2013,
        description: "Partial calvaria + mandible",
        significance: "465–610 cc; mosaic primitive/derived features; contemporaneous with early H. sapiens",
        citation: "Berger et al. 2015, eLife 4:e09560. DOI: 10.7554/eLife.09560",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["41.jpg"]
    },
    {
        id: 42,
        species: "Homo naledi",
        specimen: "DH1–DH5 + 1550 specimens",
        age: "286 ± 50 ka",
        ageNumeric: 0.286,
        location: "Dinaledi Chamber, Rising Star Cave, South Africa",
        discoverer: "Hunter, Tucker (cavers); Berger team",
        yearDiscovered: 2013,
        description: "≥15 individuals",
        significance: "Evidence of possible deliberate body disposal",
        citation: "Hawks et al. 2017, eLife 6:e24232. DOI: 10.7554/eLife.24232",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["42.webp"]
    },
    {
        id: 43,
        species: "Denisovan",
        specimen: 'Harbin cranium "Dragon Man"',
        age: ">146 ka",
        ageNumeric: 0.146,
        location: "Harbin, China",
        discoverer: "Anonymous laborer; donated 2018",
        yearDiscovered: 1933,
        description: "Near-complete cranium",
        significance: "Originally named H. longi (2021); June 2025: mtDNA and protein analysis confirmed Denisovan identity—first Denisovan skull",
        citation: "Ji et al. 2021, The Innovation 2:100132. DOI: 10.1016/j.xinn.2021.100132; Fu et al. 2025",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["43.avif", "43b.png"]
    },
    // Late Pleistocene diversity (300–30 ka)
    {
        id: 44,
        species: "Homo floresiensis",
        specimen: 'LB1 "Flo" (holotype)',
        age: "80 ± 20 ka",
        ageNumeric: 0.08,
        location: "Liang Bua, Flores, Indonesia",
        discoverer: "Sutikna; Morwood, Sajono team",
        yearDiscovered: 2003,
        description: "Near-complete skeleton (~40%): skull, pelvis, limbs",
        significance: "~380 cc; 1.06 m tall; insular dwarfism; associated Oldowan-like tools",
        citation: "Brown et al. 2004, Nature 431:1055–1061. DOI: 10.1038/nature02999",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["44.jpg", "44b.webp"]
    },
    {
        id: 45,
        species: "Homo luzonensis",
        specimen: "CCH6 (holotype)",
        age: "92 ± 42 ka",
        ageNumeric: 0.092,
        location: "Callao Cave, Luzon, Philippines",
        discoverer: "Piper (identified); Mijares, Détroit team",
        yearDiscovered: 2007,
        description: "Teeth + phalanges; 13 fossils from 3+ individuals",
        significance: "Mosaic australopith-like and Homo features; possible second island dwarf",
        citation: "Détroit et al. 2019, Nature 568:181–186. DOI: 10.1038/s41586-019-1067-9",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["45.jpg"]
    },
    {
        id: 46,
        species: "Homo neanderthalensis",
        specimen: "Feldhofer 1 (holotype)",
        age: "~40 ka",
        ageNumeric: 0.04,
        location: "Neander Valley, Germany",
        discoverer: "Fuhlrott",
        yearDiscovered: 1856,
        description: "Calvaria + postcranials",
        significance: "First recognized early human fossil; named species 1864; mtDNA sequenced",
        citation: "Schmitz et al. 2002, PNAS 99:13342–13347. DOI: 10.1073/pnas.192464099",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["46.webp"]
    },
    {
        id: 47,
        species: "Homo neanderthalensis",
        specimen: "Gibraltar 1",
        age: "90 ± 30 ka",
        ageNumeric: 0.09,
        location: "Gibraltar",
        discoverer: "Flint",
        yearDiscovered: 1848,
        description: "Near-complete adult female skull",
        significance: "First adult Neanderthal skull discovered (8 years before Feldhofer); examined by Darwin",
        citation: "Busk 1865, BAAS Rep. 34:91–92",
        primaryPaperUrl: "https://books.google.com/books/about/Report_Of_The_British_Association_For_Th.html?id=e7xZAAAAcAAJ",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["47.webp"]
    },
    {
        id: 48,
        species: "Homo neanderthalensis",
        specimen: 'La Chapelle-aux-Saints 1 "Old Man"',
        age: "~60 ka",
        ageNumeric: 0.06,
        location: "Corrèze, France",
        discoverer: "Bouyssonie brothers",
        yearDiscovered: 1908,
        description: "Near-complete skeleton",
        significance: ">1600 cc; first near-complete Neanderthal; severe arthritis shows group care; confirmed burial",
        citation: "Boule 1911–1913, Ann. Paléontol. 6–8. DOI: 10.5962/bhl.title.77337",
        primaryPaperUrl: "https://doi.org/10.5962/bhl.title.77337",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["48.jpg"]
    },
    {
        id: 49,
        species: "Homo neanderthalensis",
        specimen: "La Ferrassie 1",
        age: "47 ± 7 ka",
        ageNumeric: 0.047,
        location: "Dordogne, France",
        discoverer: "Capitan, Peyrony",
        yearDiscovered: 1909,
        description: "Near-complete skeleton",
        significance: "1641 cc—second largest hominin skull; complete middle ear ossicles; intentional burial",
        citation: "Gómez-Olivencia et al. 2018, J. Hum. Evol. 117:13–32. DOI: 10.1016/j.jhevol.2017.12.004",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["49a.jpg", "49b.webp"]
    },
    {
        id: 50,
        species: "Homo neanderthalensis",
        specimen: 'Shanidar 1 "Nandy"',
        age: "40 ± 5 ka",
        ageNumeric: 0.04,
        location: "Shanidar Cave, Iraqi Kurdistan",
        discoverer: "Solecki",
        yearDiscovered: 1957,
        description: "Near-complete skeleton",
        significance: "Multiple severe injuries survived for years; evidence of compassionate care",
        citation: "Trinkaus 1983, The Shanidar Neandertals, Academic Press",
        primaryPaperUrl: "https://books.google.com/books/about/The_Shanidar_Neandertals.html?id=fi2AAAAAMAAJ",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["50a.webp", "50b.webp"]
    },
    {
        id: 51,
        species: "Homo neanderthalensis",
        specimen: 'Shanidar 4 "Flower Burial"',
        age: "~73 ka",
        ageNumeric: 0.073,
        location: "Shanidar Cave, Iraqi Kurdistan",
        discoverer: "Solecki",
        yearDiscovered: 1960,
        description: "Adult male skeleton",
        significance: 'Famous "flower burial" (controversial); unique mortuary cluster',
        citation: "Solecki 1975, Science 190:880–881. DOI: 10.1126/science.190.4217.880",
        primaryPaperUrl: "https://doi.org/10.1126/science.190.4217.880",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["51a.png", "51b.png", "51c.png", "51d.png", "51e.png", "51f.png"]
    },
    {
        id: 52,
        species: "Homo neanderthalensis",
        specimen: 'Kebara 2 "Moshe"',
        age: "60.5 ± 0.5 ka",
        ageNumeric: 0.0605,
        location: "Mount Carmel, Israel",
        discoverer: "Bar-Yosef, Vandermeersch",
        yearDiscovered: 1983,
        description: "Most complete Neanderthal postcranium: vertebrae, ribs, pelvis, arms, hands",
        significance: "First Neanderthal hyoid bone (speech implications); bell-shaped ribcage",
        citation: "Bar-Yosef et al. 1992, Curr. Anthropol. 33:497–550. DOI: 10.1086/204112",
        primaryPaperUrl: "https://doi.org/10.1086/204112",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["52.jpg"]
    },
    {
        id: 53,
        species: "Homo neanderthalensis",
        specimen: "Amud 1",
        age: "60 ± 10 ka",
        ageNumeric: 0.06,
        location: "Upper Galilee, Israel",
        discoverer: "Suzuki",
        yearDiscovered: 1961,
        description: "Near-complete skeleton",
        significance: "1736–1740 cc—largest cranial capacity of any human; 1.78 m tall",
        citation: "Suzuki & Takai 1970, The Amud Man, Keigaku",
        primaryPaperUrl: "https://books.google.com/books/about/The_Amud_Man_and_His_Cave_Site.html?id=YpUKAQAAIAAJ",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["53.webp"]
    },
    {
        id: 54,
        species: "Homo neanderthalensis",
        specimen: "Tabun C1",
        age: "~170 ka",
        ageNumeric: 0.17,
        location: "Mount Carmel, Israel",
        discoverer: "Garrod–1934",
        yearDiscovered: 1929,
        description: "Near-complete adult female skeleton",
        significance: "One of oldest Levantine Neanderthals; cold-adapted body",
        citation: "McCown & Keith 1939, Stone Age of Mount Carmel II",
        primaryPaperUrl: "https://archive.org/details/stoneageofmountc02join",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["54.webp"]
    },
    {
        id: 55,
        species: "Denisovan",
        specimen: "Denisova 3",
        age: ">50 ka",
        ageNumeric: 0.05,
        location: "Denisova Cave, Russia",
        discoverer: "Shunkov, Derevianko team",
        yearDiscovered: 2008,
        description: "Distal finger phalanx",
        significance: "First Denisovan identified; complete genome sequenced; 4–6% ancestry in Melanesians",
        citation: "Krause et al. 2010, Nature 464:894–897. DOI: 10.1038/nature08976; Reich et al. 2010, Nature 468:1053–1060. DOI: 10.1038/nature09710",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["55.jpg"]
    },
    {
        id: 56,
        species: "Neanderthal–Denisovan hybrid",
        specimen: 'Denisova 11 "Denny"',
        age: "~90 ka",
        ageNumeric: 0.09,
        location: "Denisova Cave, Russia",
        discoverer: "Slon team analysis (bone); 2018 (identification)",
        yearDiscovered: 2012,
        description: "Long bone fragment",
        significance: "First-generation Neanderthal-Denisovan hybrid; Neanderthal mother, Denisovan father",
        citation: "Slon et al. 2018, Nature 561:113–116. DOI: 10.1038/s41586-018-0455-x",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["56.jpg"]
    },
    {
        id: 57,
        species: "Denisovan",
        specimen: "Xiahe mandible",
        age: "≥160 ka",
        ageNumeric: 0.16,
        location: "Baishiya Karst Cave, Tibet",
        discoverer: "Chen, Zhang, Hublin team (found); 2019 (identified)",
        yearDiscovered: 1980,
        description: "Right half mandible with 2 molars",
        significance: "First confirmed Denisovan outside Siberia; identified via proteins; explains Tibetan EPAS1 adaptation",
        citation: "Chen et al. 2019, Nature 569:409–412. DOI: 10.1038/s41586-019-1139-x",
        era: "late-pleistocene",
        eraLabel: "Late Pleistocene",
        images: ["57.png"]
    },
    // Early and archaic Homo sapiens (315 ka–30 ka)
    {
        id: 58,
        species: "Homo sapiens",
        specimen: "Jebel Irhoud 1/10/11",
        age: "315 ± 34 ka",
        ageNumeric: 0.315,
        location: "Jebel Irhoud, Morocco",
        discoverer: "Hublin",
        yearDiscovered: 2004,
        description: "Multiple partial: cranium, face, mandible",
        significance: "Oldest H. sapiens; modern face + archaic braincase; pan-African origin",
        citation: "Hublin et al. 2017, Nature 546:289–292. DOI: 10.1038/nature22336",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["58.webp"]
    },
    {
        id: 59,
        species: "Homo sapiens",
        specimen: "Omo I",
        age: "≥233 ka",
        ageNumeric: 0.233,
        location: "Omo Kibish, Ethiopia",
        discoverer: "R. Leakey",
        yearDiscovered: 1967,
        description: "Partial skeleton including cranium",
        significance: "Unequivocal modern human features; oldest definitive East African H. sapiens",
        citation: "Vidal et al. 2022, Nature 601:579–583. DOI: 10.1038/s41586-021-04275-8",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["59.jpg"]
    },
    {
        id: 60,
        species: "Homo sapiens",
        specimen: "Omo II",
        age: "≥233 ka",
        ageNumeric: 0.233,
        location: "Omo Kibish, Ethiopia",
        discoverer: "R. Leakey",
        yearDiscovered: 1967,
        description: "Calvaria",
        significance: "More primitive than Omo I; shows early H. sapiens variation",
        citation: "Day 1969, Nature 222:1135–1138. DOI: 10.1038/2221135a0",
        primaryPaperUrl: "https://doi.org/10.1038/2221135a0",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["60.jpg"]
    },
    {
        id: 61,
        species: "Homo sapiens",
        specimen: "BOU-VP-16/1 (Herto)",
        age: "157 ± 3 ka",
        ageNumeric: 0.157,
        location: "Middle Awash, Ethiopia",
        discoverer: "White",
        yearDiscovered: 1997,
        description: "Near-complete adult cranium",
        significance: "~1450 cc; intermediate morphology; cut marks suggest mortuary practice; proposed subspecies H. s. idaltu",
        citation: "White et al. 2003, Nature 423:742–747. DOI: 10.1038/nature01669",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["61.jpg"]
    },
    {
        id: 62,
        species: "Homo sapiens",
        specimen: "Florisbad",
        age: "~259 ka",
        ageNumeric: 0.259,
        location: "Free State, South Africa",
        discoverer: "Dreyer",
        yearDiscovered: 1932,
        description: "Fragmentary cranium",
        significance: "~1400 cc; transitional features; supports African multiregionalism",
        citation: "Grün et al. 1996, Nature 382:500–501. DOI: 10.1038/382500a0",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["62.jpg"]
    },
    {
        id: 63,
        species: "Homo sapiens",
        specimen: "Skhul V",
        age: "90 ± 10 ka",
        ageNumeric: 0.09,
        location: "Mount Carmel, Israel",
        discoverer: "Garrod, McCown",
        yearDiscovered: 1931,
        description: "Near-complete skeleton",
        significance: "Key evidence for early Out-of-Africa dispersal; intentional burial",
        citation: "Stringer et al. 1989, Nature 338:756–758. DOI: 10.1038/338756a0",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["63.webp"]
    },
    {
        id: 64,
        species: "Homo sapiens",
        specimen: "Qafzeh 9",
        age: "104 ± 12 ka",
        ageNumeric: 0.104,
        location: "Qafzeh, Israel",
        discoverer: "Vandermeersch",
        yearDiscovered: 1965,
        description: "Good cranial preservation",
        significance: "Intentional burial with grave goods",
        citation: "Valladas et al. 1988, Nature 331:614–616. DOI: 10.1038/331614a0",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["64.jpg"]
    },
    {
        id: 65,
        species: "Homo sapiens",
        specimen: "Klasies River",
        age: "90 ± 30 ka",
        ageNumeric: 0.09,
        location: "Eastern Cape, South Africa",
        discoverer: "Singer, Wymer",
        yearDiscovered: 1967,
        description: "Mandibles, cranial fragments",
        significance: "Earliest evidence of chin; essentially modern morphology",
        citation: "Rightmire & Deacon 1991, J. Hum. Evol. 20:131–156. DOI: 10.1016/0047-2484(91)90054-Y",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["65.png"]
    },
    {
        id: 66,
        species: "Homo sapiens",
        specimen: "Border Cave 1",
        age: "126 ± 44 ka",
        ageNumeric: 0.126,
        location: "KwaZulu-Natal, South Africa",
        discoverer: "Cookes",
        yearDiscovered: 1940,
        description: "Partial cranium",
        significance: "Globular endocranial shape; early complex behavior evidence",
        citation: "Grün et al. 1990, Nature 344:537–539. DOI: 10.1038/344537a0",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["66.webp"]
    },
    {
        id: 67,
        species: "Homo sapiens",
        specimen: "Liujiang",
        age: "28 ± 5 ka",
        ageNumeric: 0.028,
        location: "Guangxi, China",
        discoverer: "Pei Wenzhong",
        yearDiscovered: 1958,
        description: "Near-complete skeleton",
        significance: "Fully modern; represents late Pleistocene East Asian dispersal",
        citation: "Ge et al. 2024, Nat. Commun. 15:3584. DOI: 10.1038/s41467-024-47787-3",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["67.webp"]
    },
    {
        id: 68,
        species: "Homo sapiens",
        specimen: 'Lake Mungo 3 "Mungo Man"',
        age: "40 ± 2 ka",
        ageNumeric: 0.04,
        location: "NSW, Australia",
        discoverer: "Bowler",
        yearDiscovered: 1974,
        description: "Near-complete skeleton",
        significance: "Oldest human in Australia; earliest ochre ritual burial",
        citation: "Bowler et al. 2003, Nature 421:837–840. DOI: 10.1038/nature01383",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["68.webp"]
    },
    {
        id: 69,
        species: "Homo sapiens",
        specimen: "Cro-Magnon 1",
        age: "30 ± 2 ka",
        ageNumeric: 0.03,
        location: "Dordogne, France",
        discoverer: "Lartet",
        yearDiscovered: 1868,
        description: "Complete skull + postcranial",
        significance: "~1600 cc; first recognized anatomically modern human; Aurignacian tools",
        citation: "Lartet 1868, Bull. Soc. Anthropol. Paris 3:335–349. DOI: 10.3406/bmsap.1868.9547",
        primaryPaperUrl: "https://doi.org/10.3406/bmsap.1868.9547",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["69.webp"]
    },
    {
        id: 70,
        species: "Homo sapiens",
        specimen: "Misliya maxilla",
        age: "186 ± 9 ka",
        ageNumeric: 0.186,
        location: "Misliya Cave, Mount Carmel, Israel",
        discoverer: "Hershkovitz team",
        yearDiscovered: 2001,
        description: "Left maxilla with teeth (nearly complete young adult)",
        significance: "Oldest modern human outside Africa",
        citation: "Hershkovitz et al. 2018, Science 359:456–459. DOI: 10.1126/science.aap8369",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["70.jpg"]
    },
    {
        id: 71,
        species: "Homo sapiens",
        specimen: "Apidima 1",
        age: "~210 ka",
        ageNumeric: 0.21,
        location: "Apidima Cave, Mani Peninsula, Greece",
        discoverer: "Univ. of Athens team; re-analyzed Harvati, 2019",
        yearDiscovered: 1978,
        description: "Partial cranium (back of skull)",
        significance: "Potentially oldest H. sapiens in Europe",
        citation: "Harvati et al. 2019, Nature 571:500–504. DOI: 10.1038/s41586-019-1376-z",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["71.jpg"]
    },
    {
        id: 72,
        species: "Homo sapiens",
        specimen: "Tam Pà Ling",
        age: "77 ± 9 ka",
        ageNumeric: 0.077,
        location: "Tam Pà Ling Cave, Annamite Mountains, Laos",
        discoverer: "Demeter, Shackelford team",
        yearDiscovered: 2009,
        description: "Multiple individuals (TPL1-7): skull, mandibles, rib, phalanx, tibia",
        significance: "Earliest H. sapiens in mainland SE Asia",
        citation: "Freidline et al. 2023, Nat. Commun. 14:3193. DOI: 10.1038/s41467-023-38715-y",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["72.jpg"]
    },
    {
        id: 73,
        species: "Homo sapiens",
        specimen: "Ranis Cave",
        age: "45.5 ± 2 ka",
        ageNumeric: 0.0455,
        location: "Ilsenhöhle cave, Ranis, Germany",
        discoverer: "Hülle; Hublin, Weiss team, 2016–2022",
        yearDiscovered: 1932,
        description: "13 bone fragments",
        significance: "Oldest H. sapiens in northern Europe; makers of LRJ stone tools",
        citation: "Mylopotamitaki et al. 2024, Nature 626:341–346. DOI: 10.1038/s41586-023-06923-7",
        era: "sapiens",
        eraLabel: "Homo sapiens",
        images: ["73.avif"]
    }
];

// Era configuration for filtering and styling - Cohesive muted earth tones
const ERA_CONFIG = {
    'earliest': {
        label: 'Earliest Hominins',
        color: '#a78bfa',
        range: '7.0–4.2 Ma'
    },
    'australopithecus': {
        label: 'Australopithecus',
        color: '#67e8f9',
        range: '4.2–1.98 Ma'
    },
    'paranthropus': {
        label: 'Paranthropus',
        color: '#86efac',
        range: '3.5–1.0 Ma'
    },
    'early-homo': {
        label: 'Early Homo',
        color: '#fcd34d',
        range: '2.5–0.25 Ma'
    },
    'late-pleistocene': {
        label: 'Late Pleistocene',
        color: '#fca5a5',
        range: '300–30 ka'
    },
    'sapiens': {
        label: 'Homo sapiens',
        color: '#f9a8d4',
        range: '315 ka–present'
    }
};

// Helper function to get unique species
function getUniqueSpecies() {
    const species = [...new Set(FOSSIL_DATA.map(f => f.species))];
    return species.sort();
}

// Helper function to get unique locations (simplified)
function getUniqueLocations() {
    const locations = FOSSIL_DATA.map(f => {
        const parts = f.location.split(',');
        return parts[parts.length - 1].trim();
    });
    return [...new Set(locations)].sort();
}

// Export for Node-based data checks.
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { FOSSIL_DATA, ERA_CONFIG, getUniqueSpecies, getUniqueLocations };
}
